version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "kateshop"
      POSTGRES_USER: "kateshop"
      POSTGRES_PASSWORD: "kateshop"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080