// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/example": {
            "get": {
                "description": "get example message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Example api test",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetExampleResponse"
                        }
                    }
                }
            }
        },
        "/admin/talon": {
            "get": {
                "description": "get talon ID by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get talon ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "place here talon ID",
                        "name": "talonId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetTalonByIdResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Insert new talon",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Post talon",
                "parameters": [
                    {
                        "description": "place here talon ID",
                        "name": "rquestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PostTalonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PostTalonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.GetExampleResponse": {
            "type": "object",
            "properties": {
                "example": {
                    "type": "string",
                    "example": "oleg loh"
                }
            }
        },
        "domain.GetTalonByIdResponse": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "integer",
                    "example": 1
                },
                "time": {
                    "type": "string",
                    "example": "10.03.2023,10:30PM"
                },
                "userId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "domain.PostTalonRequest": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "integer",
                    "example": 1
                },
                "time": {
                    "type": "string",
                    "example": "10.03.2023,10:30PM"
                },
                "userId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "domain.PostTalonResponse": {
            "type": "object",
            "properties": {
                "talonId": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Kate Shop testing API",
	Description:      "This is a Kate server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
