basePath: /api
definitions:
  domain.GetAllUsersResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/domain.GetUserByIdResponse'
        type: array
    type: object
  domain.GetExampleResponse:
    properties:
      example:
        example: oleg loh
        type: string
    type: object
  domain.GetPhotoByIdResponse:
    properties:
      hidden:
        example: true
        type: boolean
      imagename:
        example: "1"
        type: string
      servicesId:
        example: 1
        type: integer
      url:
        example: "1"
        type: string
    type: object
  domain.GetTalonByIdResponse:
    properties:
      orderId:
        example: 1
        type: integer
      time:
        example: 10.03.2023,10:30PM
        type: string
      userId:
        example: 1
        type: integer
    type: object
  domain.GetUserByIdResponse:
    properties:
      callpreferences:
        example: "1"
        type: string
      instagram:
        example: lololo
        type: string
      orderId:
        example: 1
        type: integer
      phonenumber:
        example: "9833211233212"
        type: string
      talon:
        example: 1
        type: integer
      username:
        example: OLEG
        type: string
    type: object
  domain.PostPhotoRequest:
    properties:
      hidden:
        example: true
        type: boolean
      imagename:
        example: "1"
        type: string
      servicesId:
        example: 1
        type: integer
      url:
        example: "1"
        type: string
    type: object
  domain.PostPhotoResponse:
    properties:
      photoId:
        example: 1
        type: integer
    type: object
  domain.PostTalonRequest:
    properties:
      orderId:
        example: 1
        type: integer
      time:
        example: "2023-01-02T10:30:00Z"
        type: string
      userId:
        example: 1
        type: integer
    type: object
  domain.PostTalonResponse:
    properties:
      talonId:
        example: 1
        type: integer
    type: object
  domain.PostUserRequest:
    properties:
      callpreferences:
        example: "1"
        type: string
      instagram:
        example: lololo
        type: string
      orderId:
        example: 1
        type: integer
      phonenumber:
        example: "9833211233212"
        type: string
      talon:
        example: 1
        type: integer
      username:
        example: OLEG
        type: string
    type: object
  domain.PostUserResponse:
    properties:
      userId:
        example: 1
        type: integer
    type: object
info:
  contact: {}
  description: This is a Kate server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Kate Shop testing API
  version: "0.1"
paths:
  /admin/example:
    get:
      consumes:
      - application/json
      description: get example message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetExampleResponse'
      summary: Example api test
  /admin/photo:
    get:
      consumes:
      - application/json
      description: get photo ID by ID
      parameters:
      - description: place here photo ID
        in: query
        name: photoId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetPhotoByIdResponse'
      summary: Get photo ID
    post:
      consumes:
      - application/json
      description: Insert new photo
      parameters:
      - description: place here photo ID
        in: body
        name: rquestBody
        required: true
        schema:
          $ref: '#/definitions/domain.PostPhotoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PostPhotoResponse'
      summary: Post photo
  /admin/talon:
    get:
      consumes:
      - application/json
      description: get talon ID by ID
      parameters:
      - description: place here talon ID
        in: query
        name: talonId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetTalonByIdResponse'
      summary: Get talon ID
    post:
      consumes:
      - application/json
      description: Insert new talon
      parameters:
      - description: place here talon ID
        in: body
        name: rquestBody
        required: true
        schema:
          $ref: '#/definitions/domain.PostTalonRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PostTalonResponse'
      summary: Post talon
  /admin/user:
    get:
      consumes:
      - application/json
      description: get user ID by ID
      parameters:
      - description: place here user ID
        in: query
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetUserByIdResponse'
      summary: Get user ID
    post:
      consumes:
      - application/json
      description: Insert new user
      parameters:
      - description: place here user ID
        in: body
        name: rquestBody
        required: true
        schema:
          $ref: '#/definitions/domain.PostUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PostUserResponse'
      summary: Post user
  /admin/users:
    get:
      consumes:
      - application/json
      description: get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetAllUsersResponse'
      summary: Get Users
      tags:
      - Users
swagger: "2.0"
